version: "3"

services:
  player-profile-service:
    image: ${SERVICE_IMAGE}
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787 -Xmx512m -Xms512m
    profiles:
      - jooq-generate
    ports:
      - "8888:8888"
      - "8787:8787"
    depends_on:
      - httpserver
      - postgres
    container_name: "player-profile-service"

  httpserver:
    image: wiremock/wiremock:latest
    volumes:
      - ./src/test/resources/integration-tests-data/mappings:/home/wiremock/mappings
      - ./src/test/resources/integration-tests-data/__files:/home/wiremock/__files
    command: --global-response-templating --print-all-network-traffic --enable-browser-proxying
    container_name: "httpserver"
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.10
    environment:
      - POSTGRES_DB=playerprofileservicedb
      - POSTGRES_USER=playerprofileservice
      - POSTGRES_PASSWORD=playerprofileservice
    ports:
      - "5432:5432"
    container_name: "player-profile-service-database"
