/*
 * This file is generated by jOOQ.
 */
package com.hunus.playerprofileservice.database.jooq.model.tables.records;


import com.hunus.playerprofileservice.database.jooq.model.tables.Devices;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceRecord extends UpdatableRecordImpl<DeviceRecord> implements Record7<UUID, String, String, String, UUID, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.device.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.device.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.device.model</code>.
     */
    public void setModel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.device.model</code>.
     */
    public String getModel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.device.carrier</code>.
     */
    public void setCarrier(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.device.carrier</code>.
     */
    public String getCarrier() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.device.firmware</code>.
     */
    public void setFirmware(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.device.firmware</code>.
     */
    public String getFirmware() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.device.player_id</code>.
     */
    public void setPlayerId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.device.player_id</code>.
     */
    public UUID getPlayerId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.device.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.device.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.device.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.device.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, String, UUID, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, String, String, UUID, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Devices.DEVICE.ID;
    }

    @Override
    public Field<String> field2() {
        return Devices.DEVICE.MODEL;
    }

    @Override
    public Field<String> field3() {
        return Devices.DEVICE.CARRIER;
    }

    @Override
    public Field<String> field4() {
        return Devices.DEVICE.FIRMWARE;
    }

    @Override
    public Field<UUID> field5() {
        return Devices.DEVICE.PLAYER_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Devices.DEVICE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Devices.DEVICE.MODIFIED;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getModel();
    }

    @Override
    public String component3() {
        return getCarrier();
    }

    @Override
    public String component4() {
        return getFirmware();
    }

    @Override
    public UUID component5() {
        return getPlayerId();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getModel();
    }

    @Override
    public String value3() {
        return getCarrier();
    }

    @Override
    public String value4() {
        return getFirmware();
    }

    @Override
    public UUID value5() {
        return getPlayerId();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public DeviceRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DeviceRecord value2(String value) {
        setModel(value);
        return this;
    }

    @Override
    public DeviceRecord value3(String value) {
        setCarrier(value);
        return this;
    }

    @Override
    public DeviceRecord value4(String value) {
        setFirmware(value);
        return this;
    }

    @Override
    public DeviceRecord value5(UUID value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public DeviceRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public DeviceRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public DeviceRecord values(UUID value1, String value2, String value3, String value4, UUID value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceRecord
     */
    public DeviceRecord() {
        super(Devices.DEVICE);
    }

    /**
     * Create a detached, initialised DeviceRecord
     */
    public DeviceRecord(UUID id, String model, String carrier, String firmware, UUID playerId, LocalDateTime created, LocalDateTime modified) {
        super(Devices.DEVICE);

        setId(id);
        setModel(model);
        setCarrier(carrier);
        setFirmware(firmware);
        setPlayerId(playerId);
        setCreated(created);
        setModified(modified);
    }
}
