/*
 * This file is generated by jOOQ.
 */
package com.hunus.playerprofileservice.database.jooq.model.tables.records;


import com.google.gson.JsonElement;
import com.hunus.playerprofileservice.database.jooq.model.tables.PlayerProfiles;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerProfileRecord extends UpdatableRecordImpl<PlayerProfileRecord> implements Record20<UUID, String, LocalDateTime, Integer, Integer, Integer, LocalDateTime, JsonElement, Integer, Integer, Integer, String, String, LocalDateTime, String, JsonElement, String, LocalDateTime, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.player_profile.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.player_profile.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.player_profile.credential</code>.
     */
    public void setCredential(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.player_profile.credential</code>.
     */
    public String getCredential() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.player_profile.last_session</code>.
     */
    public void setLastSession(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.player_profile.last_session</code>.
     */
    public LocalDateTime getLastSession() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.player_profile.total_spent</code>.
     */
    public void setTotalSpent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.player_profile.total_spent</code>.
     */
    public Integer getTotalSpent() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.player_profile.total_refund</code>.
     */
    public void setTotalRefund(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.player_profile.total_refund</code>.
     */
    public Integer getTotalRefund() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.player_profile.total_transactions</code>.
     */
    public void setTotalTransactions(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.player_profile.total_transactions</code>.
     */
    public Integer getTotalTransactions() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.player_profile.last_purchase</code>.
     */
    public void setLastPurchase(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.player_profile.last_purchase</code>.
     */
    public LocalDateTime getLastPurchase() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.player_profile.active_campaigns</code>.
     */
    public void setActiveCampaigns(JsonElement value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.player_profile.active_campaigns</code>.
     */
    public JsonElement getActiveCampaigns() {
        return (JsonElement) get(7);
    }

    /**
     * Setter for <code>public.player_profile.level</code>.
     */
    public void setLevel(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.player_profile.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.player_profile.experience</code>.
     */
    public void setExperience(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.player_profile.experience</code>.
     */
    public Integer getExperience() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.player_profile.total_playtime</code>.
     */
    public void setTotalPlaytime(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.player_profile.total_playtime</code>.
     */
    public Integer getTotalPlaytime() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.player_profile.country</code>.
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.player_profile.country</code>.
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.player_profile.language</code>.
     */
    public void setLanguage(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.player_profile.language</code>.
     */
    public String getLanguage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.player_profile.birthdate</code>.
     */
    public void setBirthdate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.player_profile.birthdate</code>.
     */
    public LocalDateTime getBirthdate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.player_profile.gender</code>.
     */
    public void setGender(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.player_profile.gender</code>.
     */
    public String getGender() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.player_profile.inventory</code>.
     */
    public void setInventory(JsonElement value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.player_profile.inventory</code>.
     */
    public JsonElement getInventory() {
        return (JsonElement) get(15);
    }

    /**
     * Setter for <code>public.player_profile.custom_field</code>.
     */
    public void setCustomField(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.player_profile.custom_field</code>.
     */
    public String getCustomField() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.player_profile.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.player_profile.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.player_profile.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.player_profile.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>public.player_profile.clan_id</code>.
     */
    public void setClanId(UUID value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.player_profile.clan_id</code>.
     */
    public UUID getClanId() {
        return (UUID) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<UUID, String, LocalDateTime, Integer, Integer, Integer, LocalDateTime, JsonElement, Integer, Integer, Integer, String, String, LocalDateTime, String, JsonElement, String, LocalDateTime, LocalDateTime, UUID> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<UUID, String, LocalDateTime, Integer, Integer, Integer, LocalDateTime, JsonElement, Integer, Integer, Integer, String, String, LocalDateTime, String, JsonElement, String, LocalDateTime, LocalDateTime, UUID> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return PlayerProfiles.PLAYER_PROFILE.ID;
    }

    @Override
    public Field<String> field2() {
        return PlayerProfiles.PLAYER_PROFILE.CREDENTIAL;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PlayerProfiles.PLAYER_PROFILE.LAST_SESSION;
    }

    @Override
    public Field<Integer> field4() {
        return PlayerProfiles.PLAYER_PROFILE.TOTAL_SPENT;
    }

    @Override
    public Field<Integer> field5() {
        return PlayerProfiles.PLAYER_PROFILE.TOTAL_REFUND;
    }

    @Override
    public Field<Integer> field6() {
        return PlayerProfiles.PLAYER_PROFILE.TOTAL_TRANSACTIONS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return PlayerProfiles.PLAYER_PROFILE.LAST_PURCHASE;
    }

    @Override
    public Field<JsonElement> field8() {
        return PlayerProfiles.PLAYER_PROFILE.ACTIVE_CAMPAIGNS;
    }

    @Override
    public Field<Integer> field9() {
        return PlayerProfiles.PLAYER_PROFILE.LEVEL;
    }

    @Override
    public Field<Integer> field10() {
        return PlayerProfiles.PLAYER_PROFILE.EXPERIENCE;
    }

    @Override
    public Field<Integer> field11() {
        return PlayerProfiles.PLAYER_PROFILE.TOTAL_PLAYTIME;
    }

    @Override
    public Field<String> field12() {
        return PlayerProfiles.PLAYER_PROFILE.COUNTRY;
    }

    @Override
    public Field<String> field13() {
        return PlayerProfiles.PLAYER_PROFILE.LANGUAGE;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return PlayerProfiles.PLAYER_PROFILE.BIRTHDATE;
    }

    @Override
    public Field<String> field15() {
        return PlayerProfiles.PLAYER_PROFILE.GENDER;
    }

    @Override
    public Field<JsonElement> field16() {
        return PlayerProfiles.PLAYER_PROFILE.INVENTORY;
    }

    @Override
    public Field<String> field17() {
        return PlayerProfiles.PLAYER_PROFILE.CUSTOM_FIELD;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return PlayerProfiles.PLAYER_PROFILE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field19() {
        return PlayerProfiles.PLAYER_PROFILE.MODIFIED;
    }

    @Override
    public Field<UUID> field20() {
        return PlayerProfiles.PLAYER_PROFILE.CLAN_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCredential();
    }

    @Override
    public LocalDateTime component3() {
        return getLastSession();
    }

    @Override
    public Integer component4() {
        return getTotalSpent();
    }

    @Override
    public Integer component5() {
        return getTotalRefund();
    }

    @Override
    public Integer component6() {
        return getTotalTransactions();
    }

    @Override
    public LocalDateTime component7() {
        return getLastPurchase();
    }

    @Override
    public JsonElement component8() {
        return getActiveCampaigns();
    }

    @Override
    public Integer component9() {
        return getLevel();
    }

    @Override
    public Integer component10() {
        return getExperience();
    }

    @Override
    public Integer component11() {
        return getTotalPlaytime();
    }

    @Override
    public String component12() {
        return getCountry();
    }

    @Override
    public String component13() {
        return getLanguage();
    }

    @Override
    public LocalDateTime component14() {
        return getBirthdate();
    }

    @Override
    public String component15() {
        return getGender();
    }

    @Override
    public JsonElement component16() {
        return getInventory();
    }

    @Override
    public String component17() {
        return getCustomField();
    }

    @Override
    public LocalDateTime component18() {
        return getCreated();
    }

    @Override
    public LocalDateTime component19() {
        return getModified();
    }

    @Override
    public UUID component20() {
        return getClanId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCredential();
    }

    @Override
    public LocalDateTime value3() {
        return getLastSession();
    }

    @Override
    public Integer value4() {
        return getTotalSpent();
    }

    @Override
    public Integer value5() {
        return getTotalRefund();
    }

    @Override
    public Integer value6() {
        return getTotalTransactions();
    }

    @Override
    public LocalDateTime value7() {
        return getLastPurchase();
    }

    @Override
    public JsonElement value8() {
        return getActiveCampaigns();
    }

    @Override
    public Integer value9() {
        return getLevel();
    }

    @Override
    public Integer value10() {
        return getExperience();
    }

    @Override
    public Integer value11() {
        return getTotalPlaytime();
    }

    @Override
    public String value12() {
        return getCountry();
    }

    @Override
    public String value13() {
        return getLanguage();
    }

    @Override
    public LocalDateTime value14() {
        return getBirthdate();
    }

    @Override
    public String value15() {
        return getGender();
    }

    @Override
    public JsonElement value16() {
        return getInventory();
    }

    @Override
    public String value17() {
        return getCustomField();
    }

    @Override
    public LocalDateTime value18() {
        return getCreated();
    }

    @Override
    public LocalDateTime value19() {
        return getModified();
    }

    @Override
    public UUID value20() {
        return getClanId();
    }

    @Override
    public PlayerProfileRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value2(String value) {
        setCredential(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value3(LocalDateTime value) {
        setLastSession(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value4(Integer value) {
        setTotalSpent(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value5(Integer value) {
        setTotalRefund(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value6(Integer value) {
        setTotalTransactions(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value7(LocalDateTime value) {
        setLastPurchase(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value8(JsonElement value) {
        setActiveCampaigns(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value9(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value10(Integer value) {
        setExperience(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value11(Integer value) {
        setTotalPlaytime(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value12(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value13(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value14(LocalDateTime value) {
        setBirthdate(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value15(String value) {
        setGender(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value16(JsonElement value) {
        setInventory(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value17(String value) {
        setCustomField(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value18(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value19(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public PlayerProfileRecord value20(UUID value) {
        setClanId(value);
        return this;
    }

    @Override
    public PlayerProfileRecord values(UUID value1, String value2, LocalDateTime value3, Integer value4, Integer value5, Integer value6, LocalDateTime value7, JsonElement value8, Integer value9, Integer value10, Integer value11, String value12, String value13, LocalDateTime value14, String value15, JsonElement value16, String value17, LocalDateTime value18, LocalDateTime value19, UUID value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerProfileRecord
     */
    public PlayerProfileRecord() {
        super(PlayerProfiles.PLAYER_PROFILE);
    }

    /**
     * Create a detached, initialised PlayerProfileRecord
     */
    public PlayerProfileRecord(UUID id, String credential, LocalDateTime lastSession, Integer totalSpent, Integer totalRefund, Integer totalTransactions, LocalDateTime lastPurchase, JsonElement activeCampaigns, Integer level, Integer experience, Integer totalPlaytime, String country, String language, LocalDateTime birthdate, String gender, JsonElement inventory, String customField, LocalDateTime created, LocalDateTime modified, UUID clanId) {
        super(PlayerProfiles.PLAYER_PROFILE);

        setId(id);
        setCredential(credential);
        setLastSession(lastSession);
        setTotalSpent(totalSpent);
        setTotalRefund(totalRefund);
        setTotalTransactions(totalTransactions);
        setLastPurchase(lastPurchase);
        setActiveCampaigns(activeCampaigns);
        setLevel(level);
        setExperience(experience);
        setTotalPlaytime(totalPlaytime);
        setCountry(country);
        setLanguage(language);
        setBirthdate(birthdate);
        setGender(gender);
        setInventory(inventory);
        setCustomField(customField);
        setCreated(created);
        setModified(modified);
        setClanId(clanId);
    }
}
