/*
 * This file is generated by jOOQ.
 */
package com.hunus.playerprofileservice.database.jooq.model;


import com.hunus.playerprofileservice.database.jooq.model.tables.Clans;
import com.hunus.playerprofileservice.database.jooq.model.tables.Devices;
import com.hunus.playerprofileservice.database.jooq.model.tables.FlywaySchemaHistory;
import com.hunus.playerprofileservice.database.jooq.model.tables.PlayerProfiles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.clan</code>.
     */
    public static final Clans CLAN = Clans.CLANS;

    /**
     * The table <code>public.device</code>.
     */
    public static final Devices DEVICE = Devices.DEVICE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.player_profile</code>.
     */
    public static final PlayerProfiles PLAYER_PROFILE = PlayerProfiles.PLAYER_PROFILE;
}
